### ISSUE TITLE
sigfox library, examples

### ISSUE THREAD

**Issue by intdb** [wisol-SFM/WSSFM20Rx_12x#2]
- It's not clear from the existing examples how to read ID/PAC or switch to CW test mode using your sigfox API. This would be a nice addition to the sigfox example. 

- The "sigfox_send_payload" function is always sending 12 bytes even when the message is shorter (fills the rest with zeroes). There should be an option to send shorter message.

**Comment by yepark-wisol** [comment]
1. You can do it with the PC tool. (development\sigfox_cfg2\tools\EXE_CONFIG2_v009.zip)
See UserManual(development\sigfox_cfg2\documentation\manual\[WISOL]UserManual_EVBSFM20R_V200.pdf).

See datasheet for AT command set.
AX-SIGFOX-D.PDF
https://www.google.co.kr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjrpp7Rto_WAhVKEbwKHYU4Aj0QFgglMAA&url=https%3A%2F%2Fwww.onsemi.com%2Fpub%2FCollateral%2FAX-SIGFOX-D.PDF&usg=AFQjCNGIXUVMIRhj3N7x52zBHsKDQxj0yQ

2. We'll update the sigfox API to send short messages later.

**Comment by intdb** [comment]
1. But can you do it programmatically without the PC tool with the use of this api?

**Comment by yepark-wisol** [comment]
For technical inquiries, please visit http://support.wisol.co.kr

There is no sigfox bypass api example, but there is a wifi bypass example.
Both are similar in usage.
Cfg_examples.c (development \ sigfox_cfg2 \ source)
cfg_examples_wifi_bypass (), cfg_examples_wifi_TCP_via_bypass ()

**Comment by intdb** [comment]
ok, thank you.

**Comment by remoteranger** [comment]
Did you figure out how to get the ID and PAC without the PC app?

**Comment by eliotstock** [comment]
Send "AT$I=10\r" for the device ID and "AT$I=11\r" for the PAC.

**Comment by remoteranger** [comment]
I'm having trouble doing that in the JTT viewer window. It says I can send the commands, but nothing shows in the window after I do.

**Comment by eliotstock** [comment]
Can't help you there, sorry. I don't really use the SDK or tools from Wisol.

**Comment by intdb** [comment]
Check the wifi bypass example, rewrite it to sigfox - it is very simmilar but not quite.
Then send the AT commands with sigfox_bypass_write_request and read them with the callback defined in sigfox_bypass_req.

**Comment by yepark-wisol** [comment]
After executing cfg_sigfox_prepare_start () function,
m_module_peripheral_ID.sigfox_device_ID and m_module_peripheral_ID.sigfox_pac_code contain values.
…..
cPrintLog(CDBG_FCTRL_INFO, “SFX ID:”);
cDataDumpPrintOut(CDBG_FCTRL_INFO, m_module_peripheral_ID.sigfox_device_ID, 4);
cPrintLog(CDBG_FCTRL_INFO, “SFX PAC CODE:”);
cDataDumpPrintOut(CDBG_FCTRL_INFO, m_module_peripheral_ID.sigfox_pac_code, 8);
…..

**Comment by intdb** [comment]
And is there finally a way to send shorter messages than 12bytes?
