### ISSUE TITLE
Free uvision MDK licence allows compiling ?

### ISSUE THREAD

**Issue by mroi-snoc** [wisol-SFM/WSSFM20Rx_12x#3]
Hello,

On document [WISOL]Development_Environment_Setup_Guide_V202, page 27, at point 8.2, while building the sigfox_cfg2_pca10040_s132.uvprojx I get a compiler licence related error:
.\_build\nrf52832_xxaa.axf: error: L6050U: The code size of this image (123928 bytes) exceeds the maximum allowed for this version of the linker.

Did I miss something ?

Thanks a lot for your help,

Maximilien.

**Comment by yepark-wisol** [comment]
If you load sigfox_cfg2_pca10040_s132_gcc.uvprojx, you can build it with GCC.

**Comment by mroi-snoc** [comment]
Thanks a lot for your help.
To compile with GCC it is worth checking in micro-vision IDE menu Project -> Manage -> Project items.. and then in the "Folders/Extensions" pane, the "Folder" field of "Use GCC Compiler..." group  should contain the path to tools\gcc-win32 folder, probably "..\..\..\..\tools\gcc-win32\"
